drop table if exists channel CASCADE;
create table Channel
(
    id              bigint generated by default as identity,
    external_id     varchar(32),
    thumbnail_url   varchar(64),
    handle          varchar(32),
    primary key (id)
);
create table Video
(
    id              bigint generated by default as identity,
    channel_id      bigint,
    external_id     varchar(32),
    publish_time    datetime,
    title           varchar(32),
    thumbnail_url   varchar(64),
    primary key (id),
    foreign key (channel_id) references Channel(id)
);