drop table if exists channel CASCADE;
create table Channel
(
    id              bigint generated by default as identity,
    external_id     varchar(32),
    thumbnail_url   varchar(64),
    handle          varchar(32),
    primary key (id)
);
-- create table Video
-- (
--     id        bigint generated by default as identity,
--     item_name varchar(10),
--     price     integer,
--     quantity  integer,
--     primary key (id)
-- );